/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __PICOTTS_SPEECH_PROVIDER_H__
#define __PICOTTS_SPEECH_PROVIDER_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.Speech.Provider */

#define PICOTTS_TYPE_SPEECH_PROVIDER (picotts_speech_provider_get_type ())
#define PICOTTS_SPEECH_PROVIDER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PICOTTS_TYPE_SPEECH_PROVIDER, PicottsSpeechProvider))
#define PICOTTS_IS_SPEECH_PROVIDER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PICOTTS_TYPE_SPEECH_PROVIDER))
#define PICOTTS_SPEECH_PROVIDER_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), PICOTTS_TYPE_SPEECH_PROVIDER, PicottsSpeechProviderIface))

struct _PicottsSpeechProvider;
typedef struct _PicottsSpeechProvider PicottsSpeechProvider;
typedef struct _PicottsSpeechProviderIface PicottsSpeechProviderIface;

struct _PicottsSpeechProviderIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_synthesize) (
    PicottsSpeechProvider *object,
    GDBusMethodInvocation *invocation,
    GVariant *arg_pipe_fd,
    const gchar *arg_text,
    const gchar *arg_voice_id,
    gdouble arg_pitch,
    gdouble arg_rate,
    gboolean arg_is_ssml,
    const gchar *arg_language);

  const gchar * (*get_name) (PicottsSpeechProvider *object);

  GVariant * (*get_voices) (PicottsSpeechProvider *object);

};

GType picotts_speech_provider_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *picotts_speech_provider_interface_info (void);
guint picotts_speech_provider_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void picotts_speech_provider_complete_synthesize (
    PicottsSpeechProvider *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void picotts_speech_provider_call_synthesize (
    PicottsSpeechProvider *proxy,
    GVariant *arg_pipe_fd,
    const gchar *arg_text,
    const gchar *arg_voice_id,
    gdouble arg_pitch,
    gdouble arg_rate,
    gboolean arg_is_ssml,
    const gchar *arg_language,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean picotts_speech_provider_call_synthesize_finish (
    PicottsSpeechProvider *proxy,
    GAsyncResult *res,
    GError **error);

gboolean picotts_speech_provider_call_synthesize_sync (
    PicottsSpeechProvider *proxy,
    GVariant *arg_pipe_fd,
    const gchar *arg_text,
    const gchar *arg_voice_id,
    gdouble arg_pitch,
    gdouble arg_rate,
    gboolean arg_is_ssml,
    const gchar *arg_language,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
GVariant *picotts_speech_provider_get_voices (PicottsSpeechProvider *object);
GVariant *picotts_speech_provider_dup_voices (PicottsSpeechProvider *object);
void picotts_speech_provider_set_voices (PicottsSpeechProvider *object, GVariant *value);

const gchar *picotts_speech_provider_get_name (PicottsSpeechProvider *object);
gchar *picotts_speech_provider_dup_name (PicottsSpeechProvider *object);
void picotts_speech_provider_set_name (PicottsSpeechProvider *object, const gchar *value);


/* ---- */

#define PICOTTS_TYPE_SPEECH_PROVIDER_PROXY (picotts_speech_provider_proxy_get_type ())
#define PICOTTS_SPEECH_PROVIDER_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PICOTTS_TYPE_SPEECH_PROVIDER_PROXY, PicottsSpeechProviderProxy))
#define PICOTTS_SPEECH_PROVIDER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), PICOTTS_TYPE_SPEECH_PROVIDER_PROXY, PicottsSpeechProviderProxyClass))
#define PICOTTS_SPEECH_PROVIDER_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), PICOTTS_TYPE_SPEECH_PROVIDER_PROXY, PicottsSpeechProviderProxyClass))
#define PICOTTS_IS_SPEECH_PROVIDER_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PICOTTS_TYPE_SPEECH_PROVIDER_PROXY))
#define PICOTTS_IS_SPEECH_PROVIDER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), PICOTTS_TYPE_SPEECH_PROVIDER_PROXY))

typedef struct _PicottsSpeechProviderProxy PicottsSpeechProviderProxy;
typedef struct _PicottsSpeechProviderProxyClass PicottsSpeechProviderProxyClass;
typedef struct _PicottsSpeechProviderProxyPrivate PicottsSpeechProviderProxyPrivate;

struct _PicottsSpeechProviderProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  PicottsSpeechProviderProxyPrivate *priv;
};

struct _PicottsSpeechProviderProxyClass
{
  GDBusProxyClass parent_class;
};

GType picotts_speech_provider_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (PicottsSpeechProviderProxy, g_object_unref)
#endif

void picotts_speech_provider_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
PicottsSpeechProvider *picotts_speech_provider_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
PicottsSpeechProvider *picotts_speech_provider_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void picotts_speech_provider_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
PicottsSpeechProvider *picotts_speech_provider_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
PicottsSpeechProvider *picotts_speech_provider_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define PICOTTS_TYPE_SPEECH_PROVIDER_SKELETON (picotts_speech_provider_skeleton_get_type ())
#define PICOTTS_SPEECH_PROVIDER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), PICOTTS_TYPE_SPEECH_PROVIDER_SKELETON, PicottsSpeechProviderSkeleton))
#define PICOTTS_SPEECH_PROVIDER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), PICOTTS_TYPE_SPEECH_PROVIDER_SKELETON, PicottsSpeechProviderSkeletonClass))
#define PICOTTS_SPEECH_PROVIDER_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), PICOTTS_TYPE_SPEECH_PROVIDER_SKELETON, PicottsSpeechProviderSkeletonClass))
#define PICOTTS_IS_SPEECH_PROVIDER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), PICOTTS_TYPE_SPEECH_PROVIDER_SKELETON))
#define PICOTTS_IS_SPEECH_PROVIDER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), PICOTTS_TYPE_SPEECH_PROVIDER_SKELETON))

typedef struct _PicottsSpeechProviderSkeleton PicottsSpeechProviderSkeleton;
typedef struct _PicottsSpeechProviderSkeletonClass PicottsSpeechProviderSkeletonClass;
typedef struct _PicottsSpeechProviderSkeletonPrivate PicottsSpeechProviderSkeletonPrivate;

struct _PicottsSpeechProviderSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  PicottsSpeechProviderSkeletonPrivate *priv;
};

struct _PicottsSpeechProviderSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType picotts_speech_provider_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (PicottsSpeechProviderSkeleton, g_object_unref)
#endif

PicottsSpeechProvider *picotts_speech_provider_skeleton_new (void);


G_END_DECLS

#endif /* __PICOTTS_SPEECH_PROVIDER_H__ */
